---
- name: Homeprod in a Box - Testing
  hosts: all
  tasks:
    - name: Import global variables
      ansible.builtin.include_vars: vars/global.yaml
    - name: Import container variables
      ansible.builtin.include_vars: vars/containers.yaml

- name: Prepare System (Set Timezone, Update Packages)
  ansible.builtin.import_playbook: playbooks/prepare.yaml
- name: Setup Docker (Install Docker)
  ansible.builtin.import_playbook: playbooks/docker.yaml
- name: Setup Traefik
  ansible.builtin.import_playbook: playbooks/traefik.yaml
