---
- name: Setup Docker
  hosts: box
  become: true

  roles:
    - geerlingguy.docker

  tasks:
    - name: Create services network
      community.docker.docker_network:
        name: services
        state: present
